### ISSUE TITLE
vpp driver throws an AttributeError exception during interface creation

### ISSUE THREAD

**Issue by naveenjoy** [naveenjoy/networking-vpp#1]
File "/opt/stack/networking-vpp/networking_vpp/agent/server.py", line 233, in bind_interface_on_host
    (iface, props) = self.create_interface_on_host(if_type, uuid, mac)
  File "/opt/stack/networking-vpp/networking_vpp/agent/server.py", line 221, in create_interface_on_host
    iface = self.vpp.create_vhostuser(path, mac)
  File "/opt/stack/networking-vpp/networking_vpp/agent/vpp.py", line 105, in create_vhostuser
    _check_retval(t)
  File "/opt/stack/networking-vpp/networking_vpp/agent/vpp.py", line 43, in _check_retval
    if t.retval != 0:
AttributeError: 'list' object has no attribute 'retval'

**Comment by naveenjoy** [comment]
This is because the interface creation fails on some occasion and the API is returning an empty list. The driver is accessing the 'retval' attribute of this empty list and raises the error. 
bind port - not in list 1bacd36d-6f53-4ea1-8123-0fad16065a89
Creating /tmp/ae9bf805-e971-42c5-9fef-8fae076a2aaf as a port
Created vhost user interface object: []
checking return value for object: []
Error: 'list' object has no attribute 'retval'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib64/python2.7/site-packages/flask_restful/**init**.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask_restful/**init**.py", line 268, in error_router
    return self.handle_error(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask_restful/**init**.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask_restful/**init**.py", line 268, in error_router
    return self.handle_error(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python2.7/site-packages/flask_restful/**init**.py", line 477, in wrapper
    resp = resource(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/flask_restful/**init**.py", line 587, in dispatch_request
    resp = meth(_args, *_kwargs)
  File "/opt/stack/networking-vpp/networking_vpp/agent/server.py", line 269, in put
    args['segmentation_id'])
  File "/opt/stack/networking-vpp/networking_vpp/agent/server.py", line 233, in bind_interface_on_host
    (iface, props) = self.create_interface_on_host(if_type, uuid, mac)
  File "/opt/stack/networking-vpp/networking_vpp/agent/server.py", line 221, in create_interface_on_host
    iface = self.vpp.create_vhostuser(path, mac)
  File "/opt/stack/networking-vpp/networking_vpp/agent/vpp.py", line 117, in create_vhostuser
    return t.sw_if_index
AttributeError: 'list' object has no attribute 'sw_if_index'
