### ISSUE TITLE
networking_vpp: Error: Recursion check hit on activating port

### ISSUE THREAD

**Issue by naveenjoy** [naveenjoy/networking-vpp#6]
2016-06-08 14:04:11.556 WARNING networking_vpp.mech_vpp [req-ee3ea117-0389-467d-a696-fc0d93e8e3c8 None None] Your recursion check hit on activating port
2016-06-08 14:04:11.634 DEBUG neutron.plugins.ml2.db [req-ca1caee1-e811-412f-939a-507cce8ac943 neutron 045a85a4cdac434fb2ce3a0f48d8fb12] For port 4e6e915e-f2ed-4a9
9-a4e1-4c0e9f051efc, host sjo-smf-ubuntu-server-2, got binding levels [<neutron.plugins.ml2.models.PortBindingLevel[object at 7f88207e0f90] {port_id=u'4e6e915e-f2e
d-4a99-a4e1-4c0e9f051efc', host=u'sjo-smf-ubuntu-server-2', level=0, driver=u'vpp', segment_id=u'94bc56ec-bf3b-4930-aeb4-7563c6906cf5'}>] from (pid=5068) get_bindi
ng_levels /opt/stack/neutron/neutron/plugins/ml2/db.py:184
2016-06-08 14:04:11.673 ERROR networking_vpp.mech_vpp [req-ca1caee1-e811-412f-939a-507cce8ac943 neutron 045a85a4cdac434fb2ce3a0f48d8fb12] in postcommit, port is {'
status': 'ACTIVE', 'binding:host_id': u'sjo-smf-ubuntu-server-2', 'description': u'', 'allowed_address_pairs': [], 'extra_dhcp_opts': [], 'updated_at': '2016-06-08
T21:04:11', 'device_owner': u'compute:None', 'port_security_enabled': True, 'binding:profile': {}, 'fixed_ips': [{'subnet_id': u'b002726e-30a6-4404-8673-a80105c13d
af', 'ip_address': u'10.0.0.71'}, {'subnet_id': u'b64f2dd7-a58c-4b96-a535-bec964ea6480', 'ip_address': u'fd3e:e14d:50c0:0:f816:3eff:fef8:f53c'}], 'id': u'4e6e915e-
f2ed-4a99-a4e1-4c0e9f051efc', 'security_groups': [u'26e0d6d0-8c40-4cce-ad73-3d391d11e851'], 'device_id': u'c18ac37d-8719-47fc-8a33-c9ab9632d179', 'name': u'', 'adm
in_state_up': True, 'network_id': u'113c31d8-b17e-434d-a79e-544aeef8ac19', 'dns_name': None, 'binding:vif_details': {u'vhostuser_socket': u'/tmp/4e6e915e-f2ed-4a99
-a4e1-4c0e9f051efc', u'vhostuser_mode': u'client'}, 'binding:vnic_type': u'normal', 'binding:vif_type': u'vhostuser', 'tenant_id': u'4bc236cc3c264a0fb7afdf6ea45cb9
de', 'mac_address': u'fa:16:3e:f8:f5:3c', 'created_at': '2016-06-08T21:04:11'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/**init**.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/dist-packages/oslo_log/handlers.py", line 73, in format
    return logging.StreamHandler.format(self, record)
  File "/usr/lib/python2.7/logging/**init**.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/oslo_log/formatters.py", line 267, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/**init**.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/**init**.py", line 329, in getMessage
    msg = msg % self.args
ValueError: unsupported format character ',' (0x2c) at index 64
Logged from file mech_vpp.py, line 221

**Comment by naveenjoy** [comment]
fixed formatting error
